language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
      env: TOX_ENV=docs
    - os: linux
      sudo: false
      python: 2.7
      env: TOX_ENV=lint2
    - os: linux
      sudo: false
      python: 3.5
      env: TOX_ENV=lint3
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=py27
    - os: linux
      sudo: required
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      sudo: required
      python: 3.6
      env: TOX_ENV=py36
    - os: osx
      language: generic
      env: TOX_ENV=skipexamples

install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -fsSL https://bootstrap.pypa.io/get-pip.py | sudo python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install "tox==3.0.0"; else pip install -U tox; fi

  # ChipKIT issue: install 32-bit support for GCC PIC32
  - if [[ "$TOX_ENV" == "py27" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libc6-i386; fi

script:
  - tox -e $TOX_ENV

notifications:
  email: false

  slack:
    rooms:
      secure: JD6VGfN4+SLU2CwDdiIOr1VgwD+zbYUCE/srwyGuHavnjIkPItkl6T6Bn8Y4VrU6ysbuKotfdV2TAJJ82ivFbY8BvZBc7FBcYp/AGQ4FaCCV5ySv8RDAcQgdE12oaGzMdODiLqsB85f65zOlAFa+htaXyEiRTcotn6Y2hupatrI=
    on_failure: always
    on_success: change
